#!/bin/bash

if [ ! -f /bin/ssh ]; then
  apt-get install ssh -y
else
  echo "SSH - Already installed"
fi

sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/.*PermitEmptyPasswords.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
sed -i 's/.*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

echo "root:qazwsxedc" | chpasswd

ls /home/user
if [ ! $? -eq 0 ]; then
  mkdir /home/user
  mkdir /home/administrator
  useradd -m -d /home/user user && echo "user:password1" | chpasswd
  useradd -m -d /home/administrator administrator && echo "administrator:password1" | chpasswd
else
  echo "User Directories - Already done"
fi

echo -e "user:password1 \nadministrator:password1 \nroot:80d41c54a8ce6d26ae0bdd509db6b187140cae39b4b771269a0d006b0620e2d2" | tee /home/.passwords

if [ ! -f /bin/vim ]; then
  apt-get install vim -y
else
  echo "Vim - Already installed"
fi

echo "ALL ALL=(ALL) NOPASSWD: /bin/vim" >> /etc/sudoers

if [ ! -f /bin/socat ]; then
  apt-get install socat -y
else
  echo "socat - Already installed"
fi

if [ ! -f /bin/iptables-xml ]; then
  apt-get install iptables -y
else
  echo "Iptables - Already installed"
fi

timeout 2 nc -z -v 127.0.0.1 1025
if [ ! $? -eq 0 ]; then
  iptables -A INPUT -p tcp --dport 20 -j ACCEPT
  socat TCP-LISTEN:1025,fork,reuseaddr SYSTEM:"echo 'dXNlcjpwYXNzd29yZDE='" &
  socat TCP-LISTEN:101,fork,reuseaddr SYSTEM:"echo 'cm9vdDpIYWNrTXlQYXNzd29yZExvbA=='" &
else
  echo "Ports are already setup"
fi
