#!/bin/bash

if [ ! -f /bin/ssh ]; then
  apt-get install ssh -y
else
  echo "Alr installed"
fi

sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/.*PermitEmptyPasswords.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
sed -i 's/.*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
/etc/init.d/ssh restart

echo "root:HackMyPasswordLol" | chpasswd

if [ ! -f /home/user ]; then
  mkdir /home/user
  mkdir /home/administrator
  useradd -m -d /home/user user && echo "user:password1" | chpasswd
  useradd -m -d /home/administrator administrator && echo "administrator:password1" | chpasswd
  echo -e "user:password1 \nadministrator:password1 \nroot:SGFja015UGFzc3dvcmRMb2w=" | tee /home/user/.passwords /home/administrator/.passwords
else
  echo "alr done"
fi

if [ ! -f /bin/vim ]; then
  apt-get install vim -y
  echo "ALL ALL=(ALL) NOPASSWD: /bin/vim" >> /etc/sudoers
else
  echo "alr done"
fi

if [ ! -f /bin/socat ]; then
  apt-get install socat -y
else
  echo "alr installed"
fi

if [ ! -f /bin/iptables-xml ]; then
  apt-get install iptables -y
else
  echo "alr installed"ww

iptables -A INPUT -p tcp --dport 20 -j ACCEPT
socat TCP-LISTEN:1025,fork,reuseaddr SYSTEM:"echo 'dXNlcjpwYXNzd29yZDE='" &
socat TCP-LISTEN:101,fork,reuseaddr SYSTEM:"echo 'cm9vdDpIYWNrTXlQYXNzd29yZExvbA=='" &
